name: Daily Terraform Apply

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at midnight UTC daily
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::247253258013:role/github-actions-role-infra_certs
          aws-region: us-east-1

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0  # Adjust as needed

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform Changes
        run: terraform apply -auto-approve
